# Basic
# ====================================================

- name: Install essential packages
  apt: pkg={{ item }} state=latest
  with_items:
    - build-essential
    - wget
    - curl
    - git-core